# Vitalik's address on Ethereum Mainnet
# https://etherscan.io/address/0xd8da6bf26964af9d7eed9e03e53415d37aa96045

{
  block {
    hash
    number
    transactions(
      filter: {
        # all filters in addresses list are OR'd
        addresses: [
          { 
            from: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045"
            to: [] 
          }
          {
            from: []
            to: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045"
          }
        ]
      }
    ) {
      hash
      from {
        address
      }
      to {
        address
      }
      value
    }
  }
}
