# You'll need to create 2 webhooks - one for incoming internal transfers and one for internal outgoing transfers.

{
  block {
    hash,
    number,
    callTracerTraces(
      filter: {
        addresses: {
          # Vitalik's address on Ethereum
          # https://etherscan.io/address/0xd8da6bf26964af9d7eed9e03e53415d37aa96045
          from: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045"
          to: []
        }
      }
    ) {
      from {
        address
      }
      to {
        address
      }
      value
      type
      traceAddressPath
      subtraceCount
      # error
      # revertReason
    }
  }
}

{
  block {
    hash,
    number,
    callTracerTraces(
      filter: {
        addresses: {
          from: []
          to: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045"
        }
      }
    ) {
      from {
        address
      }
      to {
        address
      }
      value
      type
      traceAddressPath
      subtraceCount
      # error
      # revertReason
    }
  }
}