{
  block {
    hash
    number
    logs(
      filter: {
        addresses: [
          # CryptoPunks contract address on Ethereum
          # https://etherscan.io/token/0xb47e3cd837dDF8e4c57F05d70Ab865de6e193BBB
          "0xb47e3cd837dDF8e4c57F05d70Ab865de6e193BBB"
        ]
        topics: [
          # event PunkTransfer(address indexed from, address indexed to, uint256 punkIndex);
          "0x05af636b70da6819000c49f85b21fa82081c632069bb626f30932034099107d8"
        ]
      }
    ) {
      data
      topics
      index
      account {
        address
      }
      transaction {
        hash
        index
      }
    }
  }
}
