{
  block {
    hash,
    number,
    callTracerTraces {
      from {
        address
      }
      to {
        address
      }
      value
      type
      traceAddressPath
      subtraceCount
      # error
      # revertReason
    }
  }
}