# You'll need to create 2 webhooks - one for incoming ERC20 transfers and one for outgoing ERC20 transfers.

# Outgoing ERC20 transfers
{
  block {
    hash
    number
    logs(
      filter: {
        # The addresses filter is optional - you can get all outgoing ERC20 transfers for an address by removing it
        addresses: [
          # USDC contract address on Ethereum
          # https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
          "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
        ]
        topics: [
          # event Transfer(address indexed from, address indexed to, uint256 value)
          "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"
          [
            # IMPORTANT - you must pad the address because filtering topics
            # Vitalik's address
            "0x000000000000000000000000d8da6bf26964af9d7eed9e03e53415d37aa96045"
          ]
          []
        ]
      }
    ) {
      data
      topics
      index
      account {
        address
      }
      transaction {
        hash
        index
      }
    }
  }
}

# Incoming ERC20 transfers
{
  block {
    hash
    number
    logs(
      filter: {
        # The addresses filter is optional - you can get all outgoing ERC20 transfers for an address by removing it
        addresses: [
          # USDC contract address on Ethereum
          # https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
          "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
        ]
        topics: [
          # event Transfer(address indexed from, address indexed to, uint256 value)
          "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"
          []
          [
            # IMPORTANT - you must pad the address because filtering topics
            # Vitalik's address
            "0x000000000000000000000000d8da6bf26964af9d7eed9e03e53415d37aa96045"
          ]
        ]
      }
    ) {
      data
      topics
      index
      account {
        address
      }
      transaction {
        hash
        index
      }
    }
  }
}
