{
  block {
    hash
    number
    logs(
      filter: {
        # addresses: []
        # Important - event signature / topic0 must be wrapped in array to be OR'ed
        # If you plan on tracking more events - you could also use a GraphQL variable.
        topics: [
          [
            # Transfer event has is the same for ERC20, ERC721 and CryptoKitties so you'll need to check number of topics in your handler
            
            # event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
            "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"

            # event TransferSingle(address indexed operator, address indexed from, address indexed to, uint256 id, uint256 value)
            "0xc3d58168c5ae7397731d063d5bbf3d657854427343f4c083240f7aacaa2d0f62"

            # event TransferBatch(address indexed operator, address indexed from, address indexed to, uint256[] ids, uint256[] values)
            "0x4a39dc06d4c0dbc64b70af90fd698a233a518aa5d07e595d983b8c0526c8f7fb"

            # Note - CryptoPunks transfers are a bit different 
            # event PunkTransfer(address indexed from, address indexed to, uint256 punkIndex);
          "0x05af636b70da6819000c49f85b21fa82081c632069bb626f30932034099107d8"
          ]
        ]
      }
    ) {
      data
      topics
      index
      account {
        address
      }
      transaction {
        hash
        index
      }
    }
  }
}
